//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nanoFramework_ScreenColor
{
    
    internal partial class Resource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new System.Resources.ResourceManager("nanoFramework_ScreenColor.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static nanoFramework.UI.Bitmap GetBitmap(Resource.BitmapResources id)
        {
            return ((nanoFramework.UI.Bitmap)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static nanoFramework.UI.Font GetFont(Resource.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            franklin_20 = -32429,
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            rgb_bar = -19063,
        }
    }
}
